Feature/users
rishabh-vinsol/restaurant-pos pull request #7
Opened 2023-05-13 10:26 UTC by rishabh-vinsol

2023-05-15 06:19 UTC, Sparsh-Goyal-2000 requested changes

2023-05-15 06:19 UTC, Sparsh-Goyal-2000 commented on app/views/users/index.html.erb
> +    <%= render user %>
show users in table format

2023-05-15 06:19 UTC, Sparsh-Goyal-2000 commented on app/views/users/index.html.erb
> +<%= render 'shared/notice' %>
On clicking home, it should redirect to users listing

2023-05-15 06:19 UTC, Sparsh-Goyal-2000 commented on app/views/users/show.html.erb
> +  <%= button_to "Destroy this user", @user, method: :delete %>
Add a confirmation before destroying the user

2023-05-15 06:19 UTC, Sparsh-Goyal-2000 commented on config/routes.rb
> +  resources :users
add a root

2023-05-15 06:19 UTC, Sparsh-Goyal-2000 commented on app/controllers/users_controller.rb
> +    @user = User.find_by(id: params[:id])
Check if user not found
redirect to user listing if not found

2023-05-15 06:19 UTC, Sparsh-Goyal-2000 commented on app/views/users/_user.html.erb
> +<div id="<%= dom_id user %>">
Fix this to show users in table

2023-05-17 13:24 UTC, himanshumishra31 commented
Secrets yml removed in other branch.

2023-05-17 13:25 UTC, merged